version: "0.1"

environments:
  - name: master
    branch: master
    mode: pull-request

apps:
  - name: Vue Example App
    path: ""
    image-resources: true
    text-resources:
      - path: "*.vue"
        format: vue-hardcoded
