version: "0.1"

environments:
  - name: master
    branch: master
    mode: pull-request
    
apps:
  - name: Vue Hardcoded Example App
    path: ""
    text-resources:
      - path: "*.vue"
        format: vue-hardcoded
        
        
        
